name: Fix paths and deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Fix all paths for GitHub Pages
      run: |
        echo "🔧 Fixing paths for GitHub Pages..."
        
        # Fix les imports JavaScript
        find . -type f -name "*.js" \
          -not -path "./.git/*" \
          -not -path "./node_modules/*" \
          -not -path "./functions/*" \
          -exec sed -i \
            -e "s|from '/widgets/|from '/Orixis-pwa/widgets/|g" \
            -e "s|from '/src/|from '/Orixis-pwa/src/|g" \
            -e "s|from '/modules/|from '/Orixis-pwa/modules/|g" \
            -e "s|from \"/widgets/|from \"/Orixis-pwa/widgets/|g" \
            -e "s|from \"/src/|from \"/Orixis-pwa/src/|g" \
            -e "s|from \"/modules/|from \"/Orixis-pwa/modules/|g" \
            -e "s|href = '/|href = '/Orixis-pwa/|g" \
            -e "s|href = \"/|href = \"/Orixis-pwa/|g" \
            -e "s|'/widgets/|'/Orixis-pwa/widgets/|g" \
            -e "s|'/src/|'/Orixis-pwa/src/|g" \
            -e "s|'/modules/|'/Orixis-pwa/modules/|g" \
            -e "s|\"/widgets/|\"/Orixis-pwa/widgets/|g" \
            -e "s|\"/src/|\"/Orixis-pwa/src/|g" \
            -e "s|\"/modules/|\"/Orixis-pwa/modules/|g" \
            -e "s|\`/widgets/|\`/Orixis-pwa/widgets/|g" \
            -e "s|\`/src/|\`/Orixis-pwa/src/|g" \
            -e "s|\`/modules/|\`/Orixis-pwa/modules/|g" {} +
        
        # Fix les fichiers HTML
        find . -type f -name "*.html" \
          -not -path "./.git/*" \
          -not -path "./node_modules/*" \
          -not -path "./functions/*" \
          -exec sed -i \
            -e 's|href="/|href="/Orixis-pwa/|g' \
            -e 's|src="/|src="/Orixis-pwa/|g' \
            -e 's|href="./|href="./|g' \
            -e 's|src="./|src="./|g' {} +
        
        # Fix les fichiers CSS
        find . -type f -name "*.css" \
          -not -path "./.git/*" \
          -not -path "./node_modules/*" \
          -not -path "./functions/*" \
          -exec sed -i \
            -e "s|url('/|url('/Orixis-pwa/|g" \
            -e 's|url("/|url("/Orixis-pwa/|g' {} +
        
        echo "✅ All paths fixed!"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true