name: Fix paths and deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Fix all paths for GitHub Pages
      run: |
        echo "🔧 Fixing paths for GitHub Pages..."
        
        # Fix TOUS les chemins JavaScript
        find . -type f -name "*.js" \
          -not -path "./.git/*" \
          -not -path "./node_modules/*" \
          -not -path "./functions/*" \
          -exec sed -i \
            -e "s|from '/src/|from '/Orixis-pwa/src/|g" \
            -e "s|from \"/src/|from \"/Orixis-pwa/src/|g" \
            -e "s|import('/src/|import('/Orixis-pwa/src/|g" \
            -e "s|import(\"/src/|import(\"/Orixis-pwa/src/|g" \
            -e "s|'/src/utils/|'/Orixis-pwa/src/utils/|g" \
            -e "s|\"/src/utils/|\"/Orixis-pwa/src/utils/|g" \
            -e "s|'/widgets/|'/Orixis-pwa/widgets/|g" \
            -e "s|'/modules/|'/Orixis-pwa/modules/|g" \
            -e "s|\"/widgets/|\"/Orixis-pwa/widgets/|g" \
            -e "s|\"/modules/|\"/Orixis-pwa/modules/|g" \
            -e "s|href = '/|href = '/Orixis-pwa/|g" \
            -e "s|href = \"/|href = \"/Orixis-pwa/|g" {} +
        
        # Fix les fichiers HTML
        find . -type f -name "*.html" \
          -not -path "./.git/*" \
          -not -path "./node_modules/*" \
          -exec sed -i \
            -e 's|href="/|href="/Orixis-pwa/|g' \
            -e 's|src="/|src="/Orixis-pwa/|g' \
            -e 's|href="\.\./|href="../|g' \
            -e 's|src="\.\./|src="../|g' {} +
        
        # Créer un favicon.ico si manquant
        if [ ! -f favicon.ico ]; then
          echo "Creating default favicon..."
          echo -n -e '\x00\x00\x01\x00\x01\x00\x10\x10\x00\x00\x01\x00\x20\x00\x68\x04\x00\x00\x16\x00\x00\x00' > favicon.ico
        fi
        
        echo "✅ All paths fixed!"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true